### ISSUE TITLE
User Story 10: Be able to check the live closure status of dialysis care centers

### ISSUE THREAD

**Issue by yurijhang0** [yurijhang0/DialysisNow#13]
As a dialysis care patient, I want to check the live closure status of nearby dialysis care centers, so that I can avoid closed centers.

Scenario 1: The user wants to see the live closure status of the main dialysis care center
Given: the app has access to the user’s location data or the user chose a desired location or area
When: the user opens up the app and the main screen that shows the map of the user's nearby area
Then: displays the closure status on the map by color -- red: closed/green: open

**Comment by alice-w129** [comment]
Note ongoing issues between MongoDB and Flutter integration
