### ISSUE TITLE
User Story 4: Be able to input closure information

### ISSUE THREAD

**Issue by yurijhang0** [yurijhang0/DialysisNow#7]
As an informed user about dialysis care centers, I want to be able to input information about closure information, so that I can keep other users up to date

Scenario 1: The user inputs closure information for a center that previously did not have any data
Given: the user is viewing the information regarding a specific dialysis center 
When: the user clicks on add information button
Then: displays a selection screen asking what new information the user wants to add. The user then chooses the time and inputs the center’s hours. 

Scenario 2: The user updates the current displaying closure information for a center
Given: the user is viewing the information regarding a specific dialysis center
When: the user clicks on the update information button
Then: asks the user which field they want to update and allows the user to input the updated information

**Comment by alice-w129** [comment]
Note ongoing issues between MongoDB and Flutter integration -- will consider pivot to Firebase database and extend into next sprint
